import { useState, useEffect, useCallback } from "react";
import "./NewTab.css";
import Demo from "./Demo";
import Demo2 from "./Demo2";

export const NewTab = () => {
  const getTime = () => {
    const date = new Date();
    const hour = String(date.getHours()).padStart(2, "0");
    const minute = String(date.getMinutes()).padStart(2, "0");
    return `${hour}:${minute}`;
  };

  const [time, setTime] = useState(getTime());
  const [route, setRoute] = useState(
    window.location.hash.replace("#", "") || "/"
  );
  const link = "https://github.com/guocaoyi/create-chrome-ext";

  useEffect(() => {
    let intervalId = setInterval(() => {
      setTime(getTime());
    }, 1000);

    return () => {
      clearInterval(intervalId);
    };
  }, []);

  useEffect(() => {
    const onHashChange = () => {
      setRoute(window.location.hash.replace("#", "") || "/");
    };

    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  }, []);

  const goToDemo = useCallback(() => {
    window.location.hash = "/demo";
  }, []);

  const goToDemo2 = useCallback(() => {
    window.location.hash = "/demo2";
  }, []);

  const goBack = useCallback(() => {
    window.location.hash = "/";
  }, []);

  if (route === "/demo") {
    return <Demo onBack={goBack} />;
  }

  if (route === "/demo2") {
    return <Demo2 onBack={goBack} />;
  }

  return (
    <section>
      <span></span>
      <h1>{time}</h1>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <div style={{ marginTop: 12 }}>
        <button onClick={goToDemo}>Open Demo Page</button>
        <button style={{ marginLeft: 8 }} onClick={goToDemo2}>
          Open Demo 2
        </button>
      </div>
    </section>
  );
};

export default NewTab;
